//***************************************************************
//                                                              *
// This code is auto-generated by GenerateResources.tt.         *
//                                                              *
// WARNING: Changes to this code will be lost when the code is  *
// re-generated.                                                *
//                                                              * 
//***************************************************************
namespace GenerateResourceDictionaryFromResx
{
   public static class Resources
   {
      public static string CurrentCulture { get; set; } = System.Globalization.CultureInfo.CurrentUICulture.Name;
      public static string FallbackCultre {get; set; } = "en-US";

		private static readonly FallbackDictionaryWithDefaultKey<string,string> _IDS_ClipSpeed_Speed = new FallbackDictionaryWithDefaultKey<string,string>( ()=>Resources.CurrentCulture, ()=>Resources.FallbackCultre )
		{
			["de-DE"] = @"Tempo:",
			["fr-FR"] = @"Vitesse :",
			["ja-JP"] = @"速度:",
			["en-US"] = @"Speed:",
			["zh-CN"] = @"速度:",
			DefaultKey = GenerateResourceDictionaryFromResx.Resources.CurrentCulture,
			FallbackKey = GenerateResourceDictionaryFromResx.Resources.FallbackCultre
		};

		public static FallbackDictionaryWithDefaultKey<string,string> IDS_ClipSpeed_Speed => _IDS_ClipSpeed_Speed;

		private static readonly FallbackDictionaryWithDefaultKey<string,string> _IDS_ClipSpeed_Note_Audio = new FallbackDictionaryWithDefaultKey<string,string>( ()=>Resources.CurrentCulture, ()=>Resources.FallbackCultre )
		{
			["de-DE"] = @"Hinweis: Durch das Anpassen der Clipgeschwindigkeit wird die Audiowiedergabe verzerrt.",
			["fr-FR"] = @"Remarque : l’ajustement de la vitesse du clip entraîne la distorsion du son.",
			["ja-JP"] = @"注: クリップの速度を調整するとオーディオが歪みます。",
			["en-US"] = @"Note: Adjusting the Clip Speed will distort the audio.",
			["zh-CN"] = @"请注意: 调整剪辑速度将使音频失真。",
			DefaultKey = GenerateResourceDictionaryFromResx.Resources.CurrentCulture,
			FallbackKey = GenerateResourceDictionaryFromResx.Resources.FallbackCultre
		};

		public static FallbackDictionaryWithDefaultKey<string,string> IDS_ClipSpeed_Note_Audio => _IDS_ClipSpeed_Note_Audio;

		private static readonly FallbackDictionaryWithDefaultKey<string,string> _IDS_ClipSpeed_Percent = new FallbackDictionaryWithDefaultKey<string,string>( ()=>Resources.CurrentCulture, ()=>Resources.FallbackCultre )
		{
			["de-DE"] = @"% der ursprünglichen Clip_geschwindigkeit",
			["fr-FR"] = @"% de la vite_sse du clip d’origine",
			["ja-JP"] = @"% (元のクリップの速度に対する比率)(_S)",
			["en-US"] = @"% of original clip _speed",
			["zh-CN"] = @"原始剪辑速度的 %(_S)",
			DefaultKey = GenerateResourceDictionaryFromResx.Resources.CurrentCulture,
			FallbackKey = GenerateResourceDictionaryFromResx.Resources.FallbackCultre
		};

		public static FallbackDictionaryWithDefaultKey<string,string> IDS_ClipSpeed_Percent => _IDS_ClipSpeed_Percent;

		private static readonly FallbackDictionaryWithDefaultKey<string,string> _IDS_ClipSpeed_Silence = new FallbackDictionaryWithDefaultKey<string,string>( ()=>Resources.CurrentCulture, ()=>Resources.FallbackCultre )
		{
			["de-DE"] = @"_Audio durch Stille ersetzen",
			["fr-FR"] = @"_Remplacer l’audio par du silence",
			["ja-JP"] = @"オーディオを無音で置換する(_R)",
			["en-US"] = @"_Replace audio with silence",
			["zh-CN"] = @"用静音替换音频(_R)",
			DefaultKey = GenerateResourceDictionaryFromResx.Resources.CurrentCulture,
			FallbackKey = GenerateResourceDictionaryFromResx.Resources.FallbackCultre
		};

		public static FallbackDictionaryWithDefaultKey<string,string> IDS_ClipSpeed_Silence => _IDS_ClipSpeed_Silence;

		private static readonly FallbackDictionaryWithDefaultKey<string,string> _IDS_ClipSpeed_Duration = new FallbackDictionaryWithDefaultKey<string,string>( ()=>Resources.CurrentCulture, ()=>Resources.FallbackCultre )
		{
			["de-DE"] = @"Dauer:",
			["fr-FR"] = @"Durée :",
			["ja-JP"] = @"表示時間:",
			["en-US"] = @"Duration:",
			["zh-CN"] = @"持续时间：",
			DefaultKey = GenerateResourceDictionaryFromResx.Resources.CurrentCulture,
			FallbackKey = GenerateResourceDictionaryFromResx.Resources.FallbackCultre
		};

		public static FallbackDictionaryWithDefaultKey<string,string> IDS_ClipSpeed_Duration => _IDS_ClipSpeed_Duration;

		private static readonly FallbackDictionaryWithDefaultKey<string,string> _IDS_ClipSpeed_Frames = new FallbackDictionaryWithDefaultKey<string,string>( ()=>Resources.CurrentCulture, ()=>Resources.FallbackCultre )
		{
			["de-DE"] = @"Frames",
			["fr-FR"] = @"Images",
			["ja-JP"] = @"フレーム",
			["en-US"] = @"Frames",
			["zh-CN"] = @"帧",
			DefaultKey = GenerateResourceDictionaryFromResx.Resources.CurrentCulture,
			FallbackKey = GenerateResourceDictionaryFromResx.Resources.FallbackCultre
		};

		public static FallbackDictionaryWithDefaultKey<string,string> IDS_ClipSpeed_Frames => _IDS_ClipSpeed_Frames;

		private static readonly FallbackDictionaryWithDefaultKey<string,string> _IDS_ClipSpeed_Minutes = new FallbackDictionaryWithDefaultKey<string,string>( ()=>Resources.CurrentCulture, ()=>Resources.FallbackCultre )
		{
			["de-DE"] = @"Minuten",
			["fr-FR"] = @"Minutes",
			["ja-JP"] = @"分",
			["en-US"] = @"Minutes",
			["zh-CN"] = @"分钟",
			DefaultKey = GenerateResourceDictionaryFromResx.Resources.CurrentCulture,
			FallbackKey = GenerateResourceDictionaryFromResx.Resources.FallbackCultre
		};

		public static FallbackDictionaryWithDefaultKey<string,string> IDS_ClipSpeed_Minutes => _IDS_ClipSpeed_Minutes;

		private static readonly FallbackDictionaryWithDefaultKey<string,string> _IDS_ClipSpeed_Seconds = new FallbackDictionaryWithDefaultKey<string,string>( ()=>Resources.CurrentCulture, ()=>Resources.FallbackCultre )
		{
			["de-DE"] = @"Sekunden",
			["fr-FR"] = @"Secondes",
			["ja-JP"] = @"秒",
			["en-US"] = @"Seconds",
			["zh-CN"] = @"秒",
			DefaultKey = GenerateResourceDictionaryFromResx.Resources.CurrentCulture,
			FallbackKey = GenerateResourceDictionaryFromResx.Resources.FallbackCultre
		};

		public static FallbackDictionaryWithDefaultKey<string,string> IDS_ClipSpeed_Seconds => _IDS_ClipSpeed_Seconds;

		private static readonly FallbackDictionaryWithDefaultKey<string,string> _IDS_ClipSpeed_Tray = new FallbackDictionaryWithDefaultKey<string,string>( ()=>Resources.CurrentCulture, ()=>Resources.FallbackCultre )
		{
			["en-US"] = @"Clip speed",
			DefaultKey = GenerateResourceDictionaryFromResx.Resources.CurrentCulture,
			FallbackKey = GenerateResourceDictionaryFromResx.Resources.FallbackCultre
		};

		public static FallbackDictionaryWithDefaultKey<string,string> IDS_ClipSpeed_Tray => _IDS_ClipSpeed_Tray;

		private static readonly FallbackDictionaryWithDefaultKey<string,string> _IDS_Demo = new FallbackDictionaryWithDefaultKey<string,string>( ()=>Resources.CurrentCulture, ()=>Resources.FallbackCultre )
		{
			["en-US"] = @"Demo",
			DefaultKey = GenerateResourceDictionaryFromResx.Resources.CurrentCulture,
			FallbackKey = GenerateResourceDictionaryFromResx.Resources.FallbackCultre
		};

		public static FallbackDictionaryWithDefaultKey<string,string> IDS_Demo => _IDS_Demo;

   }
}