//------------------------------------
//
// This file is autogenerated.
//
//------------------------------------
namespace Hello
{
    public enum StoredNames
    {
        /*
            I am going to need to "fill in" the values from the json file here.
            I will have to use a T4 Expression Control block
        */
        Devin,
        Grace,
        Nathan,
        Colin,
        Rose,
        Ethan,
        William,
        Benjamin
    }
}
